routes.py
from flask import Blueprint, render_template, request, redirect, url_for
#from flask_sqlalchemy import SQLAlchemy
from models import *

main = Blueprint('main', __name__)

# Route for the home page to render the index.html file
@main.route('/')
def index():
    return render_template('index.html')

# Route to render the routines.html file
@main.route('/routines', methods=['GET', 'POST'])
def create_routine():
    # If createing a routine get 'name'. Upload to .db file
    if request.method == 'POST':
        # Check if routine_id exists
        routine_id = request.form.get('routine_id') 
        routine_name = request.form['name']
        # check if routine exists
        if routine_id:
            routine = Routine.query.get_or_404(routine_id)
            # update routine name
            routine.name = routine_name
        
        else:

            new_routine = Routine(name=routine_name)
            db.session.add(new_routine)
        db.session.commit()
    
    routines = Routine.query.all()
    return render_template('routines.html', routines=routines)
    
@main.route('/routine/<int:routine_id>', methods=['GET', 'POST'])
def view_routine(routine_id):
    # get routine from id field
    routine = Routine.query.get(routine_id)
    exercises = Exercise.query.all()
    if not routine:
        return "Routine not found", 404
    # get routine_exercises
    routine_exercises = routine.exercises
    if request.method == 'POST':
        #submit exercises as list
        selected_exercises = request.form.getlist('exercises')
        for exercise_id in selected_exercises:
            exercise = Exercise.query.get(exercise_id)
            if exercise and exercise not in routine.exercises:
                routine.exercises.append(exercise)
        db.session.commit()

        return redirect(url_for('main.view_routine',
            routine_id=routine.id))
        
    return render_template('routine.html', routine=routine,
        exercises= exercises, routine_exercises=routine_exercises)

@main.route('/routine_delete/<int:routine_id>', methods=['POST'])
def delete_routine(routine_id):
    routine = Routine.query.get_or_404(routine_id)
    db.session.delete(routine)
    db.session.commit()
    return redirect(url_for('main.create_routine'))

@main.route('/routine_log/<int:routine_id>', methods=['GET', 'POST'])
def log_routine(routine_id):
    routine = Routine.query.get(routine_id)
    exercises = routine.exercises
    
    if not routine:
        return "Routine not found", 404

    # If POST log create a RoutineLog and SetLog
    if request.method == 'POST':
        for exercise in exercises:
            now = datetime.now()
            reps_key = f"reps_{exercise.id}"
            weight_key = f"weight_{exercise.id}"
            if reps_key in request.form and weight_key in request.form:
                reps = request.form[reps_key]
                weight = request.form[weight_key]

                routine_log = RoutineLog(
                    date=now,
                    routine_id=routine_id
                )
                db.session.add(routine_log)
                db.session.commit()

                new_set_log = SetLog(
                    routine_log_id=routine_log.id,
                    exercise_id=exercise.id,
                    reps=reps,
                    weight=weight

                )
                db.session.add(new_set_log)
        
        db.session.commit()
        return redirect(url_for(
            'main.view_routine', routine_id=routine_id, exercises=exercises))

    return render_template(
        'log_routine.html',
        routine=routine, exercises=exercises)


@main.route('/muscle_groups', methods=['GET', 'POST'])
def muscle_groups():
    if request.method == 'POST':
        group_name = request.form['name']
        new_group = MuscleGroup(name=group_name)
        db.session.add(new_group)
        db.session.commit()

        return redirect(url_for('main.update_or_add_muscle_to_group',
            muscle_group_id=new_group.id))

    muscle_groups = MuscleGroup.query.all()
    return render_template('muscle_groups.html',
        groups=muscle_groups)

@main.route('/delete_muscle_group/<int:muscle_group_id>',
            methods=['POST'])
def delete_muscle_group(muscle_group_id):
    selected_group = MuscleGroup.query.get_or_404(muscle_group_id)
    muscles = Muscle.query.filter_by(
        muscle_group_id=muscle_group_id).all()
    for muscle in muscles:
        db.session.delete(muscle)
    db.session.delete(selected_group)
    db.session.commit()
    return redirect(url_for('main.index'))

@main.route('/muscle_group/<int:muscle_group_id>',
    methods=['GET', 'POST'])
def update_or_add_muscle_to_group(muscle_group_id):
    muscle_group = MuscleGroup.query.get_or_404(muscle_group_id)
    if request.method == 'POST':
        # Check if muscle_id exists
        muscle_id = request.form.get('muscle_id')  
        muscle_name = request.form['name']

        if muscle_id:
            muscle = Muscle.query.get_or_404(muscle_id)
            muscle.name = muscle_name
        else:
            new_muscle = Muscle(name=muscle_name,
                muscle_group_id=muscle_group.id)
            db.session.add(new_muscle)
        
        
        db.session.commit()
        return redirect(
            url_for(
                'main.update_or_add_muscle_to_group',
                muscle_group_id=muscle_group.id))
    
    # Display the current muscles in the group
    muscles_in_group = Muscle.query.filter_by(
        muscle_group_id=muscle_group.id).all()
    
    return render_template('muscle_group.html',
        muscle_group=muscle_group, muscles=muscles_in_group)

@main.route('/delete_muscle/<int:muscle_group_id>/<int:muscle_id>',
            methods=['POST'])
def delete_muscle(muscle_group_id, muscle_id):
    selected_muscle = Muscle.query.get_or_404(muscle_id)
    db.session.delete(selected_muscle)
    db.session.commit()
    return redirect(url_for(
        'main.update_or_add_muscle_to_group',
        muscle_group_id=muscle_group_id
    ))


@main.route('/exercises', methods=['GET', 'POST'])
def exercises():
    if request.method == 'POST':
        exercise_id = request.form.get('exercise_id')
        exercise_name = request.form['name']
        if exercise_id:
            exercise = Exercise.query.get_or_404(exercise_id)
            exercise.name = exercise_name
        else:
            new_exercise = Exercise(name=exercise_name)
            db.session.add(new_exercise)
        db.session.commit()
    
    exercises = Exercise.query.options(db.joinedload(Exercise.muscles_worked)).all()
    sets = SetLog.query.all()
    return render_template('exercises.html',
        exercises=exercises, sets=sets)

@main.route('/delete_exercise/<int:exercise_id>', methods=['POST'])
def delete_exercise(exercise_id):
    selected_exercise= Exercise.query.get_or_404(exercise_id)
    db.session.delete(selected_exercise)
    db.session.commit()
    return redirect(url_for('main.exercises'))

@main.route('/exercise/<int:exercise_id>', methods=['GET', 'POST'])
def view_exercise(exercise_id):
    exercise = Exercise.query.get(exercise_id)
    all_muscles = Muscle.query.all()
    if not exercise:
        return "Exercise not found", 404

    exercise_muscles = exercise.muscles_worked
    if request.method == 'POST':
        selected_muscles = request.form.getlist('muscles')
        for muscle_id in selected_muscles:
            muscle = Muscle.query.get(muscle_id)
            if muscle and muscle not in exercise.muscles_worked:
                exercise.muscles_worked.append(muscle)
        
        db.session.commit()
        # Redirect the user to the exercises page
        return redirect(url_for('main.view_exercise',
            exercise_id= exercise.id))

    return render_template('exercise.html',
        exercise=exercise, muscles=all_muscles,
        exercise_muscles= exercise_muscles)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    <title>{% block title %}Flask Fitness{% endblock %}</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    <h1>Flask Fitness</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

templates/exercise.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}

<h1>Exercise</h1>
<h2>All muscles currently listed to be worked by {{exercise.name}} </h2>
{% for muscle in exercise_muscles %}
    <p>{{muscle.name}}</p>
{% endfor %}
<h2>Select the muscles worked for {{exercise.name}}</h2>
<form method="POST" action="{{ url_for('main.view_exercise', exercise_id= exercise.id) }}">
    <label for="muscles">Muscles</label><br>
    {% for muscle in muscles %}
    <input type="checkbox" name="muscles" value="{{ muscle.id }}">{{ muscle.name }}<br>
    {% endfor %}
    <br>
    <input type="submit" value="Add muscle to exercise">
</form>
{% endblock %}

templates/exercises.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}
<h1>Add Exercises</h1>
<h2>Create an Exercise</h2>
<form action="/exercises" method="POST">
    <label for="name">Exercise Name:</label>
    <input type="text" id="name" name="name" required>
    <button type="submit">Create</button>
</form>
<h2>All Exercises</h2>
<ul>
    {% for exercise in exercises %}
    <li>
        {{exercise.id}}: 
        <form action="{{ url_for('main.exercises') }}" method="POST" style="display: inline;">
            <input type="text" name="name" value="{{ exercise.name }}" required>
            <input type="hidden" name="exercise_id" value="{{ exercise.id }}">
            <button type="submit">Change name</button>
        </form>
        {{exercise.name}}
        <form action="{{ url_for('main.view_exercise', exercise_id = exercise.id) }}" method="POST" style="display: inline;">
            <input type="hidden" name="exercise_id" value="{{ exercise.id }}">
            <select name="muscle_id">
                {% for muscle in exercise.muscles_worked %}
                    <option value="{{ muscle.id }}">{{ muscle.name }}</option>
                {% endfor %}
            </select>
            <button type="submit">Add Muscle</button>
        </form>
        <form action="{{ url_for('main.delete_exercise', exercise_id=exercise.id) }}" method="POST" style="display: inline;">
            <button type="submit" onclick="return confirm('This action will delete this exercise. Do you wish to continue?')">Delete</button>
        </form>
        <h3>Set tracker:</h3>
        <ul>
            {% for set in sets %}
                {% if set.exercise_id == exercise.id %}
                    <li>Set date: {{ set.routine_log.date }} | Set volume: {{ set.weight * set.reps }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block body %}
<div>
    <h1>Welcome lifter</h1>
    <table>
        <tr>
            <th>Muscle Groups</th>
            <th>Add exercise</th>
            <th>Routines</th>
        </tr>
        <tr>
            <th>
                <a href="/muscle_groups">Manage Muscle Groups</a>
            </th>
            <th>
                <a href="/exercises">Manage Exercises</a>
            </th>
            <th>
                <a href="/routines">Manage Routines</a>
            </th>
        </tr>
    </table>
</div>
{% endblock %}

templates/log_routine.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}
<h1>Log sets for {{routine.name}}</h1>
<form method="POST" action="{{ url_for('main.log_routine', routine_id=routine.id) }}">
    {% for exercise in exercises %}
        <h3>{{ exercise.name }}</h3>
        <input type="hidden" name="exercise_id" value="{{ exercise.id }}">
        <label for="set_reps_{{ exercise.id }}">Reps:</label>
        <input type="number" id="set_reps_{{ exercise.id }}" name="reps_{{ exercise.id }}" required>
        <label for="set_weight_{{ exercise.id }}">Weight:</label>
        <input type="number" id="set_weight_{{ exercise.id }}" name="weight_{{ exercise.id }}" step="0.01" required>
    {% endfor %}
    <br>
    <br>
    <button type="submit">Log Routine</button>
</form>
{% endblock %}

templates/muscle_group.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}
<h2>Add a Muscle to {{ muscle_group.name }}</h2>
<form action="{{ url_for('main.update_or_add_muscle_to_group', muscle_group_id=muscle_group.id) }}" method="POST">
    <label for="name">Muscle Name:</label>
    <input type="text" id="name" name="name" required>
    <button type="submit">Create</button>
</form>

<h2>Existing Muscles in this Group:</h2>
<ul>
    {% for muscle in muscles %}
        <li>{{ muscle.id }}: {{ muscle.name }}
            <form action="{{ url_for('main.update_or_add_muscle_to_group', muscle_group_id=muscle_group.id) }}" method="POST" style="display:inline;">
                <input type="hidden" name="muscle_id" value="{{ muscle.id }}">
                <input type="text" name="name" value="{{ muscle.name }}" required>
                <button type="submit">Update</button>
            </form>
            <form action="{{ url_for('main.delete_muscle', muscle_group_id=muscle_group.id, muscle_id=muscle.id) }}" method="POST" style="display:inline;">
                <button type="submit" onclick="return confirm('This action will delete this muscle. Do you wish to continue?')">Delete</button>
            </form>
        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/muscle_groups.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}
<h2>Add a Group</h2>
<form action="/muscle_groups" method="POST">
    <label for="name">Group Name:</label>
    <input type="text" id="name" name="name" required>
    <button type="submit">Create</button>
</form>
<h2>All Muscle Groups</h2>
<ul>
    {% for group in groups %}
    <li>{{group.id}}: {{group.name}}</li>
    <a href="{{ url_for('main.update_or_add_muscle_to_group', muscle_group_id=group.id) }}">Add Muscle</a>
    <br>
    <form action="{{ url_for('main.delete_muscle_group', muscle_group_id=group.id) }}" method="POST" style="display:inline;">
        <button type="submit" onclick="return confirm('This action will delete the muscle group and all assosiated muscles, do you wish to continiue?')">Delete</button>
    </form>
    {% endfor %}
</ul>
{% endblock %}

templates/navbar.html
{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/muscle_groups">Manage muscle groups</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/exercises">Manage exercises</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/routines">Manage exercise routines</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endblock %}

templates/page_not_found.html
{% extends 'base.html' %}

{% block title %}Home - Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}
<div>
    <h1>Error - page not found </h1>
</div>
{% endblock %}

templates/routine.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% include 'navbar.html' %}
{% block body %}
<h1>Exercises currently in {{routine.name}}</h1>
{% for exercise in exercises %}
    <p>{{exercise.name}}</p>
{% endfor %}
<h1>Do you wish to log a {{routine.name}} session?</h1>
<nav>
    <a href="{{ url_for('main.log_routine', routine_id= routine.id)}}">Log routine</a>
</nav>
<h1>Add exercises to a {{routine.name}}</h1>
<form method="POST" action="{{ url_for('main.view_routine', routine_id= routine.id) }}">
    <label for="exercises">Select Exercises:</label><br>
    {% for exercise in exercises %}
    <input type="checkbox" name="exercises" value="{{ exercise.id }}"> {{ exercise.name }}<br>
    {% endfor %}
    <button type="submit">Create or Update Routine</button>
</form>
{% endblock %}

templates/routines.html
{% extends 'base.html' %}

{% block title %}Flask Fitness{% endblock %}

{% block body %}
{% include 'navbar.html' %}
<h2>Create a Routine</h2>
<form action="/routines" method="POST">
    <label for="name">Routine Name:</label>
    <input type="text" id="name" name="name" required>
    <button type="submit">Create</button>
</form>
<h2>All Routines</h2>
<ul>
    {% for routine in routines %}
    <li>
        {{ routine.id }}: 
        <form action="{{ url_for('main.create_routine') }}" method="POST" style="display: inline;">
            <input type="text" name="name" value="{{ routine.name }}" required>
            <input type="hidden" name="routine_id" value="{{ routine.id }}">
            <button type="submit">Change name</button>
        </form>
        <form action="{{ url_for('main.view_routine', routine_id=routine.id) }}" method="POST" style="display: inline;">
            <input type="hidden" name="routine_id" value="{{ routine.id }}">
            <select name="exercise_id">
                {% for exercise in routine.exercises %}
                    <option value="{{ exercise.id }}">{{ exercise.name }}</option>
                {% endfor %}
            </select>
            <button type="submit">Add exercise or log a workout</button>
        </form>
        <form action="{{ url_for('main.delete_routine', routine_id=routine.id) }}" method="POST" style="display: inline;">
            <button type="submit" onclick="return confirm('This action will delete this routine. Do you wish to continue?')">Delete</button>
        </form>
    </li>
    {% endfor %}
</ul>
{% endblock %}